# Generated by Django 4.1.5 on 2023-01-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción de la lista de tareas', max_length=50, verbose_name='Descripción'),
        ),
    ]
