# Generated by Django 4.1.5 on 2023-01-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todolist_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_complete',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(help_text='Titulo de la tarea', max_length=50, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción de la lista de tareas', max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(help_text='Nombre de la lista de tareas', max_length=50, verbose_name='Nombre'),
        ),
    ]
